name       : python3-bsddb3
version    : 6.2.1
release    : 4
source     :
    - https://pypi.python.org/packages/73/73/58954679be79a1c6031a421c81f3c8e283cd700455ad3af1de7da8fabd67/bsddb3-6.2.1.tar.gz : 319a599236b0843a36c17749c0041c18a07ef28dbe9539064fd7c0fff972567c
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for Oracle Berkeley DB
description: |
    Python bindings for Oracle Berkeley DB
builddeps  :
    - pkgconfig(python3)
    - db5-devel
build      : |
    %python3_setup
install    : |
    %python3_install --no-compile
